### PR TITLE
Update code to compile with zig 0.8.0

### LINKED ISSUE #19: Failed to build on Linux
./src/x11.zig:886:12: error: expected type 'std.fs.file.File', found 'std.net.Stream'
    return file;
           ^

### PR DESCRIPTION
**Pull request by Hejsil**
Only tested the example. Not sure if that covers the entire lib.

fixes #19

### CODE REVIEW

**Comment by Aransentin** [comment]
Merging, but note that I am working on a rewrite of this entire library that'll likely close this repo when it's at feature-parity.
